accounts/urls.py
from django.urls import path
from .views import login_view, register_view,logout_view

app_name = 'accounts'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

do/urls.py
from django.urls import path
from .views import list_do, home, detail_do, add_do, dell_do

urlpatterns = [
    path('', home, name='home'),
    path('list_do/', list_do, name='list_do'),
    path('detail_do/<int:id>/', detail_do, name='detail_do'),
    path('add_do/', add_do, name='add_do'),
    path('dell/<int:id>', dell_do, name='dell_do'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('do.urls')),
                  path('', include('accounts.urls'), name='accounts'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +\
              static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

do/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


class Do(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    date = models.DateTimeField(null=True,blank=True)
    date_view = models.CharField(default=None, blank=True, null=True, max_length=100)
    checked = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

    # def save(self, *args, **kwarg):
    #     time = datetime.datetime.now()
    #     print(time.day)
    #     print(self.date.day)
    #     year = self.date.year - time.year
    #     month = self.date.month - time.month
    #     day = self.date.day - time.day
    #     self.date_view = f'{year}:{month}:{day}'
    #     super().save(*args, **kwarg)

do/forms.py
from django import forms
from .models import Do


class AddDoForm(forms.ModelForm):
    class Meta:
        model = Do
        fields = ['title', 'description','date']


class AddDoFormOrj(forms.Form):
    title = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea)
    date = forms.DateField()

accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.info(request,"login successfully")
            return redirect('/')
        else:
            messages.warning(request,"username or password is wrong")
    form = AuthenticationForm
    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    form = UserCreationForm
    context = {'form': form}
    return render(request, 'accounts/register.html', context=context)


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        messages.warning(request, "logout is complete")
        return redirect('/')

do/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Do
from .forms import AddDoForm, AddDoFormOrj


def home(request):
    return render(request, 'do/home.html')


@login_required(login_url='accounts:login')
def list_do(request):
    does = Do.objects.filter(owner=request.user)
    todo_list_len = len(does)
    context = {'data': does,'todo_list_len':todo_list_len}
    if request.method == "POST":
        checks_list = request.POST.getlist('checked')
        checks_list = [int(x) for x in checks_list]
        for item in does:
            if item.id in checks_list:
                item.checked = True
                item.save()
                # Do.objects.filter(id=item.id).update(checked=True)
            else:
                item.checked = False
                item.save()
                # Do.objects.filter(id=item.id).update(checked=False)
        return render(request, 'do/list_do.html', context)
    return render(request, 'do/list_do.html', context)


@login_required(login_url='accounts:login')
def detail_do(request, id):
    data = Do.objects.get(id=id)
    context = {'data': data}
    return render(request, 'do/detail_do.html', context)


@login_required(login_url='accounts:login')
def add_do(request):
    if request.method == "POST":
        form = AddDoForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = request.user
            instance.save()
            return redirect('list_do')
    form = AddDoForm()
    context = {'form': form}
    return render(request, 'do/add_do.html', context=context)


@login_required(login_url='accounts:login')
def dell_do(request, id):
    try:
        do = Do.objects.get(id=id, owner=request.user)
        do.delete()
        return redirect('list_do')
    except:
        return redirect('list_do')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}
login user
{% endblock %}
{% block content %}
    <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button class="btn btn-success" type="submit">login</button>
    </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block title %}
    register
{% endblock %}
{% block content %}
    <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button class="btn btn-success" type="submit">register</button>
    </form>
{% endblock %}

do/templates/do/add_do.html
{% extends 'base.html' %}
{% block title %}
    Add Do
{% endblock %}
{% block content %}


    <div class="container create-form-container">
        <h1>Add Do</h1>
        <form class="create-todo-form" action="" method="POST">
            <div class='input-container'>
                <label for="">{{ form.title.label }}</label>
                <input class="form-control" type="text" name="title" id="id_work">
                <p class='helper-text'>please write your job</p>
            </div>
            <div class='input-container'>
                <label for="">{{ form.description.label }}</label>
                <textarea class="form-control" type="text" name="description" id="id_date"></textarea>
                <p class='helper-text'>here you can write a description required!</p>
            </div>
            <div class='input-container'>
                <label for="">{{ form.date.label }}</label>
                <input class="form-control" type="datetime-local" name="date" id="id_date">
                <p class='helper-text'>here you can pick a date and time for your job. not required!</p>
            </div>
            <button class='btn btn-primary' type="submit">add</button>
            {% csrf_token %}
        </form>
    </div>
{% endblock %}

do/templates/do/detail_do.html
{% extends 'base.html' %}
{% block title %}

    detail
{% endblock %}
{% block content %}
    <h2>{{ data.title }}</h2>
    <smal>{{ data.date }}</smal>
    <hr>
    <p>{{ data.description }}</p>
{% endblock %}

do/templates/do/home.html
{% extends 'base.html' %}
{% block title %}
    Home
{% endblock %}
{% block content %}
    <h1>Home page</h1>
    <h3><a href="{% url 'list_do' %}">List Doing</a></h3>
{% endblock %}

do/templates/do/list_do.html
{% extends 'base.html' %}
{% block title %}
    List Doing
{% endblock %}
{% block content %}
    <div class='list-container'>
        {% if todo_list_len == 0 %}
            <div>
                <h3>nothing here ...</h3>
                <a class='link' href="{% url 'add_do' %}">you can add a job to do from here</a>
            </div>
        {% else %}
            <div class="todo-list-container">
                <form method="POST" action="{% url 'list_do' %}" id='todo-list-form'>
                    {% csrf_token %}
                    <div class="todo-list">
                        <ul class="list-group">
                            {% for item in data %}
                                <li class="list-group-item todo-item">
                                    <div class="todo-item-content">
                                        <input class="check-input form-check-input {% if item.checked %}job-done-input{% endif %}"
                                               {% if item.checked %}checked{% endif %} type="checkbox"
                                               name='checked' value="{{ item.id }}" aria-label="...">
                                        <div class="{% if item.checked %}job-done-text{% endif %} job-text">
                                            <h6>{{ item.title }}</h6>
                                            <p>{{ item.date }}</p>
                                        </div>
                                    </div>
                                    <div class="todo-item-action">
                                        <a class='btn btn-danger'
                                           href="{% url 'dell_do' item.id %}">Delete</a>
                                        <a class='btn btn-secondary'
                                           href="{% url 'dell_do' item.id %}">Edit</a>
                                    </div>
                                </li>
                            {% endfor %}
                            <a class='btn btn-light' href="{% url 'add_do' %}"> Add New Work</a>
                        </ul>
                    </div>

                    <button class='btn btn-primary' id='print-paper'>print</button>
                </form>
            </div>
        {% endif %}

    </div>

    <script>
        let check_input = document.getElementsByName('checked');
        let form = document.getElementById('todo-list-form')
        let print_btn = document.getElementById('print-paper')
        console.log(check_input);
        check_input.forEach(element => {
            element.addEventListener('click', function () {
                form.submit()
            })
        });
        print_btn.addEventListener('click', function () {
            print()
        })

    </script>

{% endblock %}








{#<h1>List Of Do</h1>#}
{#<form method="POST">#}
{#    {% csrf_token %}#}
{#    {% for  %}#}
{#        <div class="list-group">#}
{##}
{#            <label class="list-group-item">#}
{#                <input class="form-check-input me-1" {% if item.checked %}checked{% endif %} type="checkbox"#}
{#                       name="checked" value="{{ item.id }}">#}
{#                {{ item.title }}#}
{#                <a href="{% url 'dell_do' item.id %}">delete</a>#}
{#            </label>#}
{##}
{#        </div>#}
{#    {% endfor %}#}
{#    <button type="submit" class="btn btn-success">submit</button>#}
{#</form>#}
{#<a href="/">#}
{#    <button href="{% url 'home' %}" type="button" class="btn btn-success mt-3">Back</button>#}
{#</a>#}
{#</div>#}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body class="bg-secondary">
<div class="container">
    {% include 'nav.html' %}


    {% include 'messages.html' %}

    {% block content %}{% endblock %}

</div>
</body>
</html>

templates/messages.html
{% if messages %}
    {% for msg in messages %}
        <h4 {% if msg.tags %} class="alert alert-{{ msg.tags }}"{% endif %}>{{ msg }}</h4>
    {% endfor %}

{% endif %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">nasagh</a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'list_do' %}">List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'add_do' %}">Add</a>
                </li>
            </ul>
        </div>
        {% if user.is_authenticated %}
            <form action="{% url 'accounts:logout' %}" method='POST'>
                {% csrf_token %}

                <button class="btn btn-primary m-1">logout</button>

            </form>
        {% else %}
            <a href="{% url 'accounts:login' %}">
                <button type="button" class="btn btn-primary m-1">login</button>
            </a>
            <a href="{% url 'accounts:register' %}">
                <button type="button" class="btn btn-primary m-1">register</button>
            </a>

        {% endif %}
    </div>
</nav>